require( 'prototypes.items' )
require( 'prototypes.item-groups' )
require( 'prototypes.crafting-categories' )
require( 'prototypes.entities' )
require( 'prototypes.recipes' )
require( 'prototypes.animations' )
require( 'prototypes.sounds' )
require( 'prototypes.sprites' )
