-- https://wiki.factorio.com/Tutorial:Mod_settings
-- local mod_prefix = 'maintenance-madness-reloaded-'
-- data:extend( {
-- {
--     type = '',  -- bool-setting, int-setting, string-setting, double-setting
--     name = '',
--     setting_type = '',
--     default_value = true,
--     order = 'a1'
-- }
-- } )
