insulate( 'util.round', function()
    local round = require( 'util/round' )

    describe( 'when precision isn\'t informed', function()
        it( 'should default to precision = 1', function()
            assert.is.equal( 0, round( 0.05 ) )
            assert.is.equal( 0, round( 0.1 ) )
            assert.is.equal( 0, round( 0.2 ) )
            assert.is.equal( 0, round( 0.3 ) )
            assert.is.equal( 0, round( 0.49 ) )
            assert.is.equal( 1, round( 0.6 ) )
            assert.is.equal( 1, round( 0.7 ) )
            assert.is.equal( 1, round( 0.8 ) )
            assert.is.equal( 1, round( 0.9 ) )
            assert.is.equal( 1, round( 1.0 ) )
            assert.is.equal( 1, round( 1.1 ) )
            assert.is.equal( 1, round( 1.2 ) )
            assert.is.equal( 1, round( 1.3 ) )
            assert.is.equal( 1, round( 1.4 ) )

            assert.is.equal( -1, round( -0.6 ) )
            assert.is.equal( -1, round( -0.7 ) )
            assert.is.equal( -1, round( -0.8 ) )
            assert.is.equal( -1, round( -0.9 ) )
            assert.is.equal( -1, round( -1.0 ) )
            assert.is.equal( -1, round( -1.1 ) )
            assert.is.equal( -1, round( -1.2 ) )
            assert.is.equal( -1, round( -1.3 ) )
            assert.is.equal( -1, round( -1.4 ) )
        end )

    end )

    describe( 'when precision is specified', function()
        it( 'should round to the specified precision', function()
            local precision = 25

            assert.is.equal( 0, round( 1, precision ) )
            assert.is.equal( 0, round( 5, precision ) )
            assert.is.equal( 0, round( 10, precision ) )
            assert.is.equal( 0, round( 12, precision ) )
            assert.is.equal( 0, round( 12.4, precision ) )
            assert.is.equal( precision, round( 12.5, precision ) )
            assert.is.equal( precision, round( 12.6, precision ) )
            assert.is.equal( precision, round( 20, precision ) )
            assert.is.equal( precision, round( 24, precision ) )
            assert.is.equal( precision, round( 25, precision ) )
            assert.is.equal( precision, round( 26, precision ) )
            assert.is.equal( precision, round( 30, precision ) )
            assert.is.equal( precision, round( 35, precision ) )
            assert.is.equal( precision, round( 37, precision ) )
            assert.is.equal( precision, round( 37.4, precision ) )
            assert.is.equal( 2 * precision, round( 37.5, precision ) )
            assert.is.equal( 2 * precision, round( 37.6, precision ) )
            assert.is.equal( 2 * precision, round( 45, precision ) )
            assert.is.equal( 2 * precision, round( 49, precision ) )
            assert.is.equal( 2 * precision, round( 50, precision ) )
        end )
    end )
end )
